---
- name: Detect current user
  register: s3cmd_current
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
  tags:
    - s3cmd

- name: Write client config
  ansible.builtin.template:
    src: config.j2
    dest: "{{ s3cmd_current.home }}/.s3cfg"
    owner: "{{ s3cmd_current.name }}"
    group: "{{ s3cmd_current.group }}"
    mode: u=rw,g=r,o=r
  tags:
    - s3cmd

...
