# Standards: 0.1
---
- name: Detect current user
  register: s3cmd_current
  user:
    name: "{{ username }}"
    state: present
  tags:
    - s3cmd

- name: Write client config
  template:
    src: config.j2
    dest: "{{ s3cmd_current.home }}/.s3cfg"
  tags:
    - s3cmd

...
